### ISSUE TITLE
Mount point /run/media/mmcblk0p2 is not the default for the average SteamDeck user

### ISSUE THREAD

**Issue by halcyonhippo** [CommitteeOfZero/polyversal-coz-linux-patcher#14]
The /run/media/mmcblk0p2/ path is the path to the SD card on 64GB models because they use an eMMC memory module for storage which allocates the mmcblk0p1 space. This makes the SD card port 0p2. On 256GB and 512GB models they use an SSD and do not have an eMMC so their SD card port will be /run/media/mmcblk0p1. This will cause the flatpak mod and STEAM_COMPAT_MOUNTS values to be incorrect, resulting in a failure for the script to find the game if a user of one of the larger model SteamDecks has installed the game to an SD card.

**Comment by halcyonhippo** [comment]
My conclusion that the 0p2 allocation is for 64GB decks is incorrect. More research is needed. The issue is most likely that the test SD card being used to decide the path for the script has multiple partions. 0p2 would reference be the 2nd partition on that card. Most users will likely only have a single partition and the value should therefor be mmcblk0p1.

**Comment by ArcanaOfSouls** [comment]
This was tested on at least one 512 GB Steam Deck. If I have time, I'll check on this by the end of this weekend. I have a 512 GB model myself and know that this ran just fine, but what you're saying makes sense. I might have installed it to the SD card, though. Either way, thanks for pointing this out. It's good to take as many system configurations into account as possible.

**Comment by Macitron** [comment]
Found this article for finding the partition on which a file is located https://www.cyberciti.biz/faq/linux-unix-command-findout-on-which-partition-file-directory-exits/

Getting the partition device itself looks to be as simple as `df /path/to/file | grep -E '/.*' | cut -f 1 -d ' '`. I would make a pull request myself, but I don't actually know what file flatpak needs access to for the script to succeed (i.e. the patch installer exe vs the steam game dir).

**Comment by halcyonhippo** [comment]
Hmm, that could work if one could find the paths. I wonder if there's a way to read the configured Steam library paths from one of the steam config files. That would cover all cases of extra mount points on any Linux, not just SteamDeck.

**Comment by ArcanaOfSouls** [comment]
This is great work! Thank you both!

If someone wants to submit a PR to handle this, that would be great. We'll take a look at authoring one ourselves sometime soon if no one else has time, but it might not be till next week since we're pretty busy with other projects for the time being. It's probably not terribly complicated, to be honest.

Then again: This script itself is not terribly complicated. It simply generalizes and automates existing processes.

**Comment by halcyonhippo** [comment]
Haven't tested this, but I think it's worth a check. I've seen a few instances where apps just use `/run/media`. It is pretty broad, but if it works, it's probably better than the current hard-coded mount path.
