### ISSUE TITLE
Issue for installs using other languages than English

### ISSUE THREAD

**Issue by SeleDreams** [CommitteeOfZero/polyversal-coz-linux-patcher#17]
I'm leaving this comment because the way the current script is setup only accounts for english systems using relative paths of the download folder.
The issue is that on system setups that aren't english (such as french), distros like Ubuntu name the download folder in French instead of english. So instead of being `~/Downloads` it ends up being `~/Téléchargements` thus makes the script fail pretty quickly
I attempted to give it an absolute path but the script doesn't account for it and still tries to append it to the path expecting a Downloads folder
I think a solution should be found. Either expecting an absolute path. either finding a way to get the name of the download folder for the current locale of the system

**Comment by halcyonhippo** [comment]
Yeah, the script isn't all that fancy yet. There's some substantial work being done by another community member (not officially associated with CoZ) that has rebuilt the script with some good QoL improvements. One of them is working from the user-specified full path as opposed to hard-coding it to ~/Downloads.

Hopefully it will get merged in here sometime in the not too distant future.
