### ISSUE TITLE
Steam Deck - LanguageBarrier exception

### ISSUE THREAD

**Issue by Skretkowicz** [CommitteeOfZero/polyversal-coz-linux-patcher#18]
Hello,

I installed this patch before on my Steam Deck without any issues. However, the console broke and I got a new one. Unofrtunately, on the new SD I cannot get the patch to work, I am following all the steps exactly like before but I am getting following error

LanguageBarrier exception
json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected [', {', or a literal

Any idea what could cause this?

**Comment by halcyonhippo** [comment]
@Skretkowicz 

Sorry for the super late reply. Development of this seems to have stalled. Ultimately the issue you're experiencing most likely has to do with flatpak permission issues which this version does not handle very well. 

That said, one of the forks on this project has done some extensive work on making a more robust patch launcher script. I recommend checking it out here: https://github.com/Macitron/polyversal-linux-coz-patcher
